<a href="https://colab.research.google.com/github/shinjeongdong/MLDeeplearningStudy/blob/main/%5BPyTorch%5D/%5BPyTorch%5D_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#A[]이면 A로 인덱싱하겠다는 뜻 = 조건을 통해 A의 일부를 꺼낸다 = 조건에 맞는 데이터를 꺼낸다.\\\
#print(A[A>3]) #A>3일때 True인 원소들만 꺼냄
#슬라잇 ㅡ인덱싱 잘라오겠다는 뜻
import torch
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = torch.tensor([1,2,3.1,4]) # 하나로도 실수면 자동으로 실수타입
print(b.dtype)
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [ ]:
A = torch.tensor([[1,2,3],[3,4,5]])
print(A)
print(A.shape) #[2,3]
print(A.ndim) #차원수 = 2
print(A.numel()) # 전체 성분의 수 6개

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [ ]:
print(torch.zeros(5)) #5개의 원소를 가진 0
print(torch.zeros_like(A)) # A와 같은 shape를 갖는 0으로만 구성된.
print(torch.ones(5)) #이건 1으로 해줌
print(torch.zeros(3,3)) #직접 크기 지정가능
print(torch.arange(3,10,2)) #range랑 같은건데 tensor모양으로 만들어 줌
print(torch.arange(0,1,0.1)) #소수점 가능
print(torch.linspace(0,1,10)) #0부터 1까지 10개를(끝이 무조건 1이여야됨) 만들어달라는 뜻임.

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = a+b
print(c)

tensor([5, 7, 9])


In [ ]:
A = torch.tensor([[1,2,3],[1,2,3]])
B = torch.tensor([[4,5,6],[1,1,1]])
C = A + B
D = A - B
print(C)
print(D)
print()
print(A*B) # Hadamard product 우리가 아는 행렬곱 기호는 @임
print(A/B)
print(B**2)

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [ ]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) #이게 진짜 행렬곱

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


pytorch의 인덱싱과 슬라이싱


In [ ]:
a = torch.tensor([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) #하나만 쓰면 행에대한 인덱싱
print(A[-1])
print(A[1:])
print(A[:]) # A출력
print(A[0][2]) # 0행리스트에 2번째 인덱스 = 3
print(A[0,2]) #위에것이랑 동일한데 리스트랑 다르게 이런것도 가능함
print(A[1,:]) # 1행의 원소 전부
print(A[1,0:3:2]) #1번째 행의? 0~3미만(2)까지의 인덱스에서? 2씩더하라 => 4,6
print(A[:,2]) #모든 행에서 2번째 인덱스 원소만
print(A[:][2]) # A 전체에서 → 그 A전체에서 index 2행을 선택"

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [ ]:
A = torch.tensor([[[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
                  [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape)
print(A[0,1,2])

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)


고오급 인덱싱

In [ ]:
print(A)
A[[0,1,1,0],[0,1,2,1],[3,3,2,1]] #0,0,3 짜리 = 3, 1,1,3 짜리 = 19, 1,2,2 짜리 = 22로 채우겠다

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


tensor([ 3, 19, 22,  5])

In [ ]:
#boolean 인덱싱 실용적이니까 외우자
a = [1,2,3,4,5,3,3]
print(a==3) #false
A = torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A>3) #리스트와 다르게 각 성분마다 True,False로 표시함
print(A[A>3]) #A>3에 해당하는 원소들만 꺼냄

A[A>3] = 100 # 3보다 큰애들을 100으로 바꿔라
print(A) #이런것도 가능함. ( 3보다 큰것들을 100으로 바꿈)

A = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B  = torch.tensor([True, False, False, True])
print(A[B,:]) #B의조건에 맞는 모든 행과 열을 출력

b = torch.tensor([1,2,3,4,])
print(b[[True,True,False,False]])

False
tensor([[False, False, False,  True],
        [ True, False,  True, False]])
tensor([4, 5, 7])
tensor([[  1,   2,   3, 100],
        [100,   3, 100,   3]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [ ]:
#tensor로 인덱싱
a = torch.tensor([1,2,3,4,5])
A = a[2]
print(A)
A = a[ torch.tensor(2) ]# torch.tensor를 인덱스 안에다?
print(A)
A = a[ torch.tensor([[2,2,2],[3,3,3]])]
print(A) # 2번째 인덱스 [3,3,3]모양 하나 3번재 인덱스인 [4,4,4]로 하나
#A[[i, j, k]] → [A[i], A[j], A[k]] 이런느낌으로 이해하면됨.

a = torch.tensor([[1,2,3],[4,5,6]])
print(a[ torch.tensor(0) ]) # 1 2 3
A = a[ torch.tensor([[0,1],[1,1]])]
print(A.shape)
print(A) #위에랑 비슷한 느낌. [[[a(0)],[a(1)]],[[a(1)],[a(1)]]으로 만들어짐


tensor(3)
tensor(3)
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [ ]:
#문제
a = torch.tensor([[1,2,3],[4,5,6]])

A = a[ torch.tensor([[0,1],[1,1]])]
print(A)


tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])
