<a href="https://colab.research.google.com/github/shinjeongdong/MLDeeplearningStudy/blob/main/%5BPyTorch%5D/%5BPyTorch%5D_2__autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch as t

In [ ]:
x = t.tensor([1.],requires_grad=True)
print(x)


tensor([1.], requires_grad=True)


In [ ]:
x = t.tensor([1.])
print(x)
print(x.requires_grad)

x.requires_grad = True
print(x)
print(x.requires_grad)

tensor([1.])
False
tensor([1.], requires_grad=True)
True


In [ ]:
x = t.tensor([1.],requires_grad= True)
y = x**2
print(y) # PowBackward0 가 붙어있다

print(x.grad)
y.backward()
print(x.grad) # y=x**2를 미분한 2x에 1을 대입한 gd값

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])


In [ ]:
x = t.tensor([1.],requires_grad=True)
y = x**2
print(y)
y.retain_grad() # 이걸 하면 y.grad도 볼수있다.

z = 3 * y
print(z)

z.backward() #requres_grad 가 True인 변수에 대해서 미분 x에대한 미분 dz/dx
print(x.grad) # 체인룰로 알아냄 z/y * y/x
print(y.grad) #3y를 y로 미분 = 3

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])
tensor([3.])


In [ ]:
x = t.tensor([1.],requires_grad=True)
y = x**2
z = 3 * y

y.backward()
print(x.grad)

tensor([2.])


In [ ]:
x = t.tensor([1.],requires_grad=True)
a = x**2
b = a+1
print(b)
c = b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [ ]:
#z.backward()를 했을때 이 z가 가지고잇는 모든 requires_grad가 true인 변수에 대해서 미분함
x = t.tensor([1.],requires_grad=True)
y = t.tensor([1.],requires_grad=True)
z = 2*x**2 + y**2
print(z)
z.backward()
print(x.grad)
print(y.grad)


tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [ ]:
x = t.tensor([1.],requires_grad=True)
y = t.tensor([1.],requires_grad=True)
z = y*x**2

z.backward()
print(x.grad) # 2
print(y.grad) # 1

tensor([2.])
tensor([1.])


In [ ]:
#스칼라를 벡터로 미분
x = t.tensor([1., 2., 3.],requires_grad=True)
y = t.sum(x**2)
y.backward()

print(y)

print(x.grad)# 행렬 미분임 => 2 4 6


tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [ ]:
#transfer learning 할 때 필요
x = t.tensor([1.],requires_grad=True)
x.requires_grad = False

y = x**2

print(y)
# y.backward() #=> error

tensor([1.])


In [ ]:
#detach?

x = t.tensor([2.],requires_grad= True)
x2 = x.detach() # detach는 requies_grad=False인 새로운 텐서를 만드는것 clone비슷
print(x)
print(x2)


tensor([2.], requires_grad=True)
tensor([2.])


In [ ]:
#디태치 사용 용도?
x = t.tensor([1.],requires_grad= True)
y = x**2
z = y.detach() # x로 만든것을 상수로 사용하고 싶은 것. y.reuqires_grad= False 이런식으로 중간에 상수로 못바꿈
w = y+z # x**2 + x**2가 아닌 x**2+1이랑 같다

w.backward()
print(x.grad) #2

tensor([2.])


In [ ]:
# 많이 쓰이는 torch.no_gard
x = t.tensor([1.],requires_grad= True)
# 체인룰을 위해 계속 grad_fn을 update 하니까 grad_fn 잠시 안계산하고 싶을때 t.no_grad
# 모델 테스트땐 불필요하게 메모리 쓸 필요가없으니
with t.no_grad():
  y = x**2
  print(x.requires_grad)
  print(y) # with안에 계산되는 애는 grad_fn이 안붙

print(x.requires_grad)
# y.backward() #error
y = x**2
print(y)

x = t.tensor([1.],requires_grad= True)
x.requires_grad = False
y = x**2
print(x.requires_grad)
print(y)

True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)
False
tensor([1.])
